export const rwTableContract = {
    source: {
        project: 'ml-ware',
        componentPath: 'resources/js/Components/RwTable.vue',
        extractedAt: '2026-03-18',
    },
    publicApi: {
        props: [
            'data',
            'columns',
            'tableId',
            'idKey',
            'initialHeight',
            'horizontalScroll',
            'checkboxColumn',
            'checkedRows',
            'globalSearch',
            'showRecordCount',
            'rowQuantitySelect',
            'rowOptions',
            'menuItems',
            'inlineUpdateRoute',
            'inlineDeleteRoute',
            'beforeInlineDelete',
            'charts',
            'excel',
            'cellStyle',
            'cellClass',
            'startOnMount',
            'initialData',
            'autoEditLastRowFirstField',
            'inlineCreate',
            'inlineCreateRoute',
            'inlineCreateButton',
            'inlineCreateDefaults',
            'manualOrdering',
            'manualOrderField',
            'rowMenu',
            'rowMenuItems',
            'managed',
            'dataSource',
            'urlSync',
            'columnsParamMode',
            'paramMap',
            'responseMap',
            'options',
            'serverSide',
            'sortField',
            'sortOrder',
            'i18n',
        ],
        emits: [
            'on-cell-click',
            'on-menu-item-click',
            'on-row-menu-item-click',
            'change',
            'update:checkedRows',
        ],
    },
    requestProtocol: {
        defaults: {
            page: 'page',
            rowsPerPage: 'rowsPerPage',
            sortField: 'sortField',
            sortOrder: 'sortOrder',
            global: 'global',
            filters: 'filters',
            filterModes: 'filterModes',
            filterTypes: 'filterTypes',
            selectionFilter: 'selectionFilter',
            selectedRowIds: 'selectedRowIds',
            columns: 'columns',
        },
    },
    responseProtocol: {
        defaults: {
            data: 'data',
            total: 'total',
            current: 'current_page',
            last: 'last_page',
        },
    },
};

export const rwTableFeatureMatrix = {
    phase0: {
        baselineParityTarget: true,
        featureGroups: [
            'core-table-rendering',
            'sorting-and-filtering',
            'managed-mode-inertia-axios',
            'infinite-scroll',
            'column-config-and-resize',
            'inline-editing',
            'inline-create-delete',
            'row-menu-and-keyboard-navigation',
            'chart-config-and-rendering',
            'excel-config-and-export',
            'localstorage-persistence',
        ],
    },
};
